### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by benoithudson** [Unity-Technologies/VHACD-deprecated#10]
liblibvhacd.dylib is compiled for Intel only.

I'd contribute a PR but this package seems to use a fork of the original -- or at least the entry points aren't in the current master at https://github.com/kmammou/v-hacd.git

**Comment by at669** [comment]
Hi, thanks for pointing that out--this repository is currently undergoing some changes; please hold as we sort it out! I've filed an internal ticket for further investigation and follow-up.

[Ticket#: AIRO-1610]

**Comment by at669** [comment]
@benoithudson as a question in the interim as the repository gets reorganized, have you made (or do you plan to make) any changes to the source code in order to recompile the library for Apple Silicon support? 

The source code is currently at [jasonmeisel/v-hacd-unity](https://github.com/jasonmeisel/v-hacd-unity), a fork of the source you mentioned.

**Comment by benoithudson** [comment]
No changes at all seem to be required to support M1, just recompiling works fine.

I had to add `extern "C"` entry points to the C++ code by hand to match the `[DllImport]` you use in C#. I can't see it in jasonmeisel's fork either.

**Comment by at669** [comment]
~~@benoithudson, this repository will be archived in favor of [Unity-Technologies/VHACD](https://github.com/Unity-Technologies/VHACD), which includes the source code for the compiled libraries.~~
